#!/usr/bin/env/python
import os
for line in open('C:/Users/Limbo/Desktop/result.CSV '):
    ID = line.split(',')[0]
    normal = line.split(',')[4]
    tumor = line.split(',')[2]
    fh = open('C:/data/%s.pbs '%ID,'a+')
    fh.writelines('#PBS -N %s\n'%ID)
    fh.writelines('#PBS -l walltime=25:00:00\n#PBS -l mem=4gb\n#PBS -l nodes=1:ppn=1\n#PBS -S /bin/bash\n#PBS -q normal_3\ncd /public/home/liuxs/biosoft/nb_distribution\nref_file=/public/home/liuxs/biodata/reference/genome/gdc_hg38/GRCh38.d1.vd1.fa\n')
    fh.writelines('tumor=%s\n'%tumor)
    fh.writelines('normal=%s'%normal)
    fh.writelines('bash run_novoBreak.sh . $ref_file $tumor $normal 1 ~/tmp/%s'%ID)
    fh.close()

